#!/usr/bin/env node
// Generates calibration.local.js from environment variables.
// Usage: node setup.js && npx serve .

const fs = require('fs');

const geminiKey = process.env.GEMINI_API_KEY || '';
const groqKey   = process.env.GROQ_API_KEY   || '';
const hfToken   = process.env.HF_TOKEN || process.env.HUGGING_FACE_HUB_TOKEN || '';

const content = `// Auto-generated by setup.js — do not commit.
window.SQUAT_CONFIG_SECRETS = {
  geminiApiKey: ${JSON.stringify(geminiKey)},
  groqApiKey:   ${JSON.stringify(groqKey)},
  hfToken:      ${JSON.stringify(hfToken)},
};
`;

fs.writeFileSync('calibration.local.js', content);

console.log('calibration.local.js written.');
if (geminiKey) console.log('  geminiApiKey: set');
if (groqKey)   console.log('  groqApiKey:   set');
if (hfToken)   console.log('  hfToken:      set');
if (!geminiKey && !groqKey && !hfToken)
  console.log('  Warning: no API keys found in env.');
